config/routes.rb
LochStockSpock::Application.routes.draw do
  
  resources :batches do 
    resources :products
  end

  root :to => 'batches#index'

end

app/models/batch.rb
class Batch < ActiveRecord::Base
  # attr_accessible :arrival_date, :description, :due_date, :name, :order_date, :product, :quantity, :product_ids

  validates_presence_of :name
  # validates_presence_of :products
  validates_uniqueness_of :name

  # has_many :quantities
  # has_many :products#, :through => :quantities
  has_many :batch_products
  has_many :products, :through => :batch_products
  accepts_nested_attributes_for :batch_products#, :reject_if => lambda { |a| a[:product_id].blank? }
  after_save :delete_blank_product

  def delete_blank_product
    self.batch_products.where(:product_id =>  nil).delete_all
  end

  def to_s
    name
  end


  def arrived?
    arrival_date.nil? ? false : true
  end
end

app/models/batch_product.rb
class BatchProduct < ActiveRecord::Base
  # attr_accessible :batch_id, :product_id
	belongs_to :batch
	belongs_to :product
	has_one :quantity
	accepts_nested_attributes_for :quantity, :reject_if => lambda { |a| a[:p_quantity].blank? }
end

app/models/product.rb
class Product < ActiveRecord::Base
  # attr_accessible :description, :sku

  has_many :batch_products
  has_many :batches, :through => :batch_products
  accepts_nested_attributes_for :batch_products
  
  # belongs_to :batch

  def to_s
    sku + " - " + description
  end


end

app/models/quantity.rb
class Quantity < ActiveRecord::Base
  # attr_accessible :batch_id, :product_id, :quantity

  belongs_to :batch_product
  validates_presence_of :p_quantity
  # belongs_to :batch

  # accepts_nested_attributes_for :product

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  # GET /batches
  # GET /batches.json
  def index
    @batches = Batch.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @batches }
    end
  end

  # GET /batches/1
  # GET /batches/1.json
  def show
    @batch = Batch.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @batch }
    end
  end

  # GET /batches/new
  # GET /batches/new.json
  def new
    @batch = Batch.new
    # @quantities = @batch.quantities.build
    @batch_products = @batch.batch_products.build
    @batch_products.build_quantity
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @batch }
    end
  end

  # GET /batches/1/edit
  def edit
    @batch = Batch.find(params[:id])
    @batch_products = @batch.batch_products
    
    # @product = @batch.quantities.build.build_product
  end

  # POST /batches
  # POST /batches.json
  def create
    puts "create"
    @batch = Batch.new(batch_params)
    respond_to do |format|
      if @batch.save
        # @pb = Quantity.find_by_batch_id(@batch.id)
        format.html { redirect_to batches_path(), notice: 'Batch was successfully created.' }
        format.json { render json: @batch, status: :created, location: @batch }
      else
        format.html { render action: "new" }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /batches/1
  # PUT /batches/1.json
  def update
    puts "update"
    @batch = Batch.find(params[:id])
    respond_to do |format|
      # debugger
      if @batch.update_attributes(batch_params)
        # @pb = Quantity.find_by_batch_id(@batch.id)
        format.html { redirect_to batches_path, notice: 'Batch was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /batches/1
  # DELETE /batches/1.json
  def destroy
    @batch = Batch.find(params[:id])
    @batch.destroy

    respond_to do |format|
      format.html { redirect_to batches_url }
      format.json { head :no_content }
    end
  end

  private 
    def batch_params
      params.require(:batch).permit(:id, :name, :due_date, :description, :order_date,:arrival_date, :product_ids=>[],batch_products_attributes: [:id,:product_id, quantity_attributes: [:p_quantity,:id, :batch_product_id]] )
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/quantities_controller.rb
class QuantitiesController < ApplicationController

  def edit
    @batch = Batch.find(params[:id])
    @q=@batch.quantities[]
    respond_to do |format|
      puts @q
      if @batch.quantities.update_attributes(@q)
        format.html { redirect_to @q, notice: 'Quantity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @q.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @batch = Batch.find(params[:id])
    @q = Quantity.find_all_by_batch_id(Quantity.find(params[:id]).batch_id)

    respond_to do |format|
      if @q.update_attributes(params[:id])
        format.html { redirect_to @q, notice: 'Quanitiy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @q.errors, status: :unprocessable_entity }
      end
    end

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/batches/_form.html.erb
<%= nested_form_for(@batch) do |f| %>
  <% if @batch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@batch.errors.count, "error") %> prohibited this batch from being saved:</h2>

      <ul>
      <% @batch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>  
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br />
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :order_date %><br />
    <%= f.date_select :order_date %>
  </div>
  <div class="field">
    <%= f.label :arrival_date %><br />
    <%= f.date_select :arrival_date %>
  </div>

  <h2>-----------------------------</h2>
  <h2>Add New Products To On This Batch</h2>
  <%product_ids = @batch.products.map(&:id) %>
  <% Product.all.each_with_index do |product,index| %>
    <div>
      <%= check_box_tag "batch[batch_products_attributes][#{index}][product_id]", product.id,(product_ids.include?(product.id) ? true : false) ,:class=>"product" %> &nbsp;&nbsp;
      <%= product.sku %>
      <% if product_ids.include?(product.id) %>
        <div><%#debugger%>
          <% ba = @batch_products.find_by_product_id(product.id)%>
          <%= f.fields_for :batch_products,ba do |p| %>
            <%= p.fields_for :quantity, (ba.quantity ? ba.quantity : ba.build_quantity) do |q| %>
              <label for="quantity">Quantity</label>
              <br />
              <%= q.number_field :p_quantity %>
              <%#= q.hidden_field :batch_product_id %>
              <%#= number_field_tag("batch[batch_products][quantity_attributes][#{index}][p_quantity]") %>
            <% end %>
          <%end %>
        </div>
      <% else %>
        <div style="display:none;">
          <%= f.fields_for :batch_products, @batch_products do |p| %>
            <%= p.fields_for :quantity do |q| %>
              <label for="quantity">Quantity</label>
              <br />
              <%= q.number_field :p_quantity %>
              <%#= q.hidden_field :batch_product_id, :value =>BatchProduct.maximum(:id).to_i.next %>
            <% end %>
          <%end %>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<script>
  $(document).ready(function(){
    $(".product").click(function(){
      $(this).next().toggle("slow");
    });
  });
</script>

app/views/batches/edit.html.erb
<h1>Editing batch</h1>

<%= render 'form' %>

<%= link_to 'Show', @batch %> |
<%= link_to 'Back', batches_path %>

app/views/batches/index.html.erb
<h1>Listing batches</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Due date</th>
    <th>Description</th>
    <th>Order date</th>
    <th>Arrival date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @batches.each do |batch| %>
  <tr>
    <td><%= batch.name %></td>
    <td><%= batch.due_date %></td>
    <td><%= batch.description %></td>
    <td><%= batch.order_date %></td>
    <td><%= batch.arrival_date %></td>
    <td><%= link_to 'Show', batch %></td>
    <td><%= link_to 'Edit', edit_batch_path(batch) %></td>
    <td><%= link_to 'Destroy', batch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Batch', new_batch_path %>

app/views/batches/new.html.erb
<h1>New batch</h1>

<%= render 'form' %>

<%= link_to 'Back', batches_path %>

app/views/batches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @batch.name %>
</p>

<p>
  <b>Due date:</b>
  <%= @batch.due_date %>
</p>

<p>
  <b>Description:</b>
  <%= @batch.description %>
</p>

<p>
  <b>Order date:</b>
  <%= @batch.order_date %>
</p>

<p>
  <b>Arrival date:</b>
  <%= @batch.arrival_date %>
</p>

<p>
  <b>Products:</b>
  <p>
    <table>
      <tr>
        <th>Sku</th>
        <th>Quantity</th>
        <th>Description</th>
      </tr>
      <% @batch.batch_products.each do |bp| %>
        <tr>
          <% p = bp.product%>
          <td>
            <%=p.sku%>
          </td>
          <td>
            &nbsp;<%=bp.quantity.p_quantity%>
          </td>
          <td>
            <%=p.description%>
          </td>
        </tr>
      <% end %>
    </table>
  </p>
</p>


<%= link_to 'Edit', edit_batch_path(@batch) %> |
<%= link_to 'Back', batches_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LochStockSpock</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sku %><br />
    <%= f.text_field :sku %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Sku</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.sku %></td>
    <td><%= product.description %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sku:</b>
  <%= @product.sku %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/quantities/edit.html.erb
<h2>Edit Product Quantities (Batch:<%= @batch.name %>)</h2>

<%= form_for(:quantity) do |f| %>

    <% @q.each do |p| %>
        <%= p.product %>

        <div class="field">
          <%= f.label :quantity %><br />
          <%= f.text_field :quantity %>
        </div>

    <% end %>

    <div class="actions">
      <%= f.submit "Add Quantities" %>
    </div>
<% end %>